### ISSUE TITLE
Unable to acquire access token

### ISSUE THREAD

**Issue by khraibani** [abjerner/Skybrud.Social.Umbraco#10]
Hi, Im getting Unable to acquire access token after I published the site, I have made sure that the I have changed the redirect URI to match the live site url. I have tried deleting the property & recreating but that didn't resolve the issue.
<img width="1120" alt="screen shot 2016-05-19 at 22 56 49" src="https://cloud.githubusercontent.com/assets/4085627/15411031/220aec8a-1e15-11e6-85aa-4a84d50c790c.png">

**Comment by abjerner** [comment]
@khraibani I can't tell for sure, but based on the error message you're seeing, I would say your server either has some network issues or the Instagram API has been down.

Do you still experience the error?

**Comment by khraibani** [comment]
@abjerner Yea, still not working. I have used your package on various sites haven't had that issue before. Do you think it could be DNS related?

**Comment by abjerner** [comment]
@khraibani Yes, it would seem like that. Do you have any way to test whether the server is able to connect to `api.instagram.com`?

**Comment by khraibani** [comment]
no not really, the hosting provider is being a nightmare on previous
enquiries.

**Comment by abjerner** [comment]
Not sure whether you found a solution for this, but I'm taking the liberty to close this issue as it seems to be a network issue rather than a code issue.
