### ISSUE TITLE
Parse error:

### ISSUE THREAD

**Issue by khraibani** [abjerner/Skybrud.Social.Umbraco#17]
I am getting the below error when I press on authorize button, can you advice on that?

![social](https://cloud.githubusercontent.com/assets/4085627/24749588/8748452c-1abb-11e7-9c31-54525a6be3da.PNG)

**Comment by abjerner** [comment]
@khraibani What was the issue causing the error?

**Comment by khraibani** [comment]
@abjerner For some The App_Plugins was included in solution, probably one of my colleague did that. So I have excluded the the folder & things went back to normal.
