### ISSUE TITLE
Twitter OAuth is ambiguous

### ISSUE THREAD

**Issue by khraibani** [abjerner/Skybrud.Social.Umbraco#22]
I went to re-authorize the application I am getting the below error:

the type 'Skybrud.Social.Umbraco.App_Plugins.Skybrud.Social.Dialogs.TwitterOAuth' is ambiguous: it could come from assembly 'h:\root\home\makeitinteractiv-001\www\interdive\bin\Skybrud.Social.Umbraco.DLL' or from assembly 'h:\root\home\makeitinteractiv-001\www\interdive\bin\Interdive.DLL'. Please specify the assembly explicitly in the type name.

![twitter-oauth](https://user-images.githubusercontent.com/4085627/34638956-5b680794-f2ce-11e7-9f01-da71d6284d60.JPG)

**Comment by abjerner** [comment]
@khraibani From what I can tell, I'm guessing your `Interdive.DLL` contains a class with the exact name (including namespace) as the one from my package. Does your DLL perhaps contain a copy of my `TwitterOAuth` class?

**Comment by khraibani** [comment]
Thank you for the help.
 Weird, I have uninstalled the package, clean the solution, rebuild, reinstalled it, and it worked.
