### ISSUE TITLE
Callback URL not approved for this client application.

### ISSUE THREAD

**Issue by BeingOnline** [abjerner/Skybrud.Social.Umbraco#25]
I have followed the instructions and am using within Umbraco 7.12.3.

I have created an app from a Twitter account and put in a dummy value in for the callback URL - I just put in website

However when I click on the button to Authorize I get, in the pop-up window the message:

"Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings"

I am running Umbraco on localhost.

Have things changed with Twitter? Or is there something I am missing?

Thanks for any help you can be.

**Comment by abjerner** [comment]
Hi @BeingOnline 

Have you entered a callback URL in the settings for your Twitter app?

![image](https://user-images.githubusercontent.com/3634580/48401010-48bf3a00-e728-11e8-9fbb-410b24236a9c.png)

I can't remember for sure, but you may just be able to enter a dummy URL.

Hope that helps ;)

**Comment by BeingOnline** [comment]
I have but I get the same message. I just put in our website – https://www.beingonline.co.uk/

Is there anything else that I should have done?

These are the steps I took:


  *   Installed your package
  *   Created the Twitter app – left default settings
  *   Created a Property Editor specifying the Consumer Key & Secret
  *   Tried to Authorize and got the message

Should it work on localhost?

Thanks for any help you can be, I really appreciate it.


Dave Hanvey
TECHNICAL SERVICES DIRECTOR
DL: 028 9073 5986
M: 07584 994414

[http://www.beingonline.co.uk/email-signatures/logo-beingonline.gif]

Belfast Office
Russell Court | 38-52 Lisburn Road | Belfast BT9 6AA

www.beingonline.co.uk<http://www.beingonline.co.uk/>

The information in this email is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it is prohibited and may be unlawful. Please contact us immediately if you are not the intended recipient. All information contained in this document is protected by © Being Communications Ltd 2006. Reg in Northern Ireland 39093 Reg Office: Russell Court, 38-52 Lisburn Road, Belfast BT9 6AA. VAT No. GB 769 8800 67.

**Comment by abjerner** [comment]
@BeingOnline I wasn't aware of this change, but Twitter are now validating the callback URL used in your code against the list of callback URLs you have specified for your Twitter app. You can read more about that here:

https://twittercommunity.com/t/action-required-sign-in-with-twitter-users-must-whitelist-callback-urls/105342

This means that if you want to use Twitter authentication on `localhost`, you'll have to specify a valid callback for `localhost` as well.

Hope that makes sense ;)

**Comment by BeingOnline** [comment]
Thanks

I really appreciate you taking the time on this one.

The bit I’m not sure about is what should be in the callback page - is it just anything that won’t generate a 404? Do I build a normal HTML page and let Twitter call it?

So for example, when I click on the authorize button it open a window with:

https://localhost:44370/App_Plugins/Skybrud.Social/Dialogs/TwitterOAuth.aspx?callback=skybrudsocial_08612381159086695&contentTypeAlias=home&propertyAlias=twitter

Is the callback parameter there telling Twitter where to callback, or does it user whatever I put in the settings?

Sorry, for all these questions, I’m just trying to get past this part then I think I should be okay.

I appreciate your help (and patience!)

Thanks
Dave




Dave Hanvey
TECHNICAL SERVICES DIRECTOR
DL: 028 9073 5986
M: 07584 994414

[http://www.beingonline.co.uk/email-signatures/logo-beingonline.gif]

Belfast Office
Russell Court | 38-52 Lisburn Road | Belfast BT9 6AA

www.beingonline.co.uk<http://www.beingonline.co.uk/>

The information in this email is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it is prohibited and may be unlawful. Please contact us immediately if you are not the intended recipient. All information contained in this document is protected by © Being Communications Ltd 2006. Reg in Northern Ireland 39093 Reg Office: Russell Court, 38-52 Lisburn Road, Belfast BT9 6AA. VAT No. GB 769 8800 67.

**Comment by BeingOnline** [comment]
Hi Anders

Thanks so much for your help. I think I have it working now.

Thanks
Dave


Dave Hanvey
TECHNICAL SERVICES DIRECTOR
DL: 028 9073 5986
M: 07584 994414

[http://www.beingonline.co.uk/email-signatures/logo-beingonline.gif]

Belfast Office
Russell Court | 38-52 Lisburn Road | Belfast BT9 6AA

www.beingonline.co.uk<http://www.beingonline.co.uk/>

The information in this email is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it is prohibited and may be unlawful. Please contact us immediately if you are not the intended recipient. All information contained in this document is protected by © Being Communications Ltd 2006. Reg in Northern Ireland 39093 Reg Office: Russell Court, 38-52 Lisburn Road, Belfast BT9 6AA. VAT No. GB 769 8800 67.

**Comment by abjerner** [comment]
@BeingOnline good to hear you found a solution 👍 

Anyways, if you're still having problems, it should be something like:

```
https://localhost:44370/App_Plugins/Skybrud.Social/Dialogs/TwitterOAuth.aspx
```

The callback URL is where the user should be redirected from Twitter.com when having approved your app. As my package needs to pick that up, the callback URL should be as above (with the domain matching the domain you're using).

**Comment by BeingOnline** [comment]
Hi

Firstly, thanks for your help previously. I am having a similar problem on another site.

The plugin just stopped updating-  it was working fine for months then recently stopped - and I thought it might be to do with the Twitter app so I created a new one and then when I click Authorize from Umbraco it gives me a yellow screen with the message ‘An existing connection was forcibly closed by the remote host’.

I have searched around online but cannot determine what might be causing that issue. Have you any ideas?

Thanks for any help you can be.

Best regards
Dave


Dave Hanvey
TECHNICAL SERVICES DIRECTOR
DL: 028 9073 5986
M: 07584 994414

[http://www.beingonline.co.uk/email-signatures/logo-beingonline.gif]

Belfast Office
Russell Court | 38-52 Lisburn Road | Belfast BT9 6AA

www.beingonline.co.uk<http://www.beingonline.co.uk/>

The information in this email is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it is prohibited and may be unlawful. Please contact us immediately if you are not the intended recipient. All information contained in this document is protected by © Being Communications Ltd 2006. Reg in Northern Ireland 39093 Reg Office: Russell Court, 38-52 Lisburn Road, Belfast BT9 6AA. VAT No. GB 769 8800 67.

**Comment by BeingOnline** [comment]
Sorry, I was able to realise that it was Twitter updating their requirement for TLS1.2 that was causing the issue.

Please ignore my email and apologies for taking up your time.

Best regards
Dave


Dave Hanvey
TECHNICAL SERVICES DIRECTOR
DL: 028 9073 5986
M: 07584 994414

[http://www.beingonline.co.uk/email-signatures/logo-beingonline.gif]

Belfast Office
Russell Court | 38-52 Lisburn Road | Belfast BT9 6AA

www.beingonline.co.uk<http://www.beingonline.co.uk/>

The information in this email is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it is prohibited and may be unlawful. Please contact us immediately if you are not the intended recipient. All information contained in this document is protected by © Being Communications Ltd 2006. Reg in Northern Ireland 39093 Reg Office: Russell Court, 38-52 Lisburn Road, Belfast BT9 6AA. VAT No. GB 769 8800 67.

From: Dave Hanvey
Sent: 21 August 2019 15:54
To: abjerner/Skybrud.Social.Umbraco <reply@reply.github.com>; abjerner/Skybrud.Social.Umbraco <Skybrud.Social.Umbraco@noreply.github.com>
Cc: support <support@beingonline.co.uk>; Mention <mention@noreply.github.com>
Subject: RE: [abjerner/Skybrud.Social.Umbraco] Callback URL not approved for this client application. (#25)

Hi

Firstly, thanks for your help previously. I am having a similar problem on another site.

The plugin just stopped updating-  it was working fine for months then recently stopped - and I thought it might be to do with the Twitter app so I created a new one and then when I click Authorize from Umbraco it gives me a yellow screen with the message ‘An existing connection was forcibly closed by the remote host’.

I have searched around online but cannot determine what might be causing that issue. Have you any ideas?

Thanks for any help you can be.

Best regards
Dave


Dave Hanvey
TECHNICAL SERVICES DIRECTOR
DL: 028 9073 5986
M: 07584 994414

[http://www.beingonline.co.uk/email-signatures/logo-beingonline.gif]

Belfast Office
Russell Court | 38-52 Lisburn Road | Belfast BT9 6AA

www.beingonline.co.uk<http://www.beingonline.co.uk/>

The information in this email is confidential and may be legally privileged. It is intended solely for the addressee. Access to this email by anyone else is unauthorised. If you are not the intended recipient any disclosure, copying, distribution or any action taken or omitted to be taken in reliance on it is prohibited and may be unlawful. Please contact us immediately if you are not the intended recipient. All information contained in this document is protected by © Being Communications Ltd 2006. Reg in Northern Ireland 39093 Reg Office: Russell Court, 38-52 Lisburn Road, Belfast BT9 6AA. VAT No. GB 769 8800 67.
