### ISSUE TITLE
Add support for manually selecting scopes in the pre-value options

### ISSUE THREAD

**Issue by abjerner** [abjerner/Skybrud.Social.Umbraco#9]
Both Facebook and Google allows developers to specify one or more scopes when authentication with their service, but the scopes are currently hardcoded Skybrud.Social.Umbraco. This should be changed for `v1.0.4` (or possibly `v1.0.3`) so that the desired scope can be specified via the pre-value options.

I have already done some work on this, but need to wrap it up before it can be released. Here are some screenshots:

![image](https://cloud.githubusercontent.com/assets/3634580/10124697/b59b44f4-655b-11e5-91f5-a4e0781e36c6.png)

![image](https://cloud.githubusercontent.com/assets/3634580/10124717/4e955924-655c-11e5-8a7a-9b3b10d23e2b.png)

**Comment by abjerner** [comment]
With the release of `v1.0.3`, the Facebook property editor and prevalue editor has now support scopes similar to shown on the first screenshot in my post above.

To get `v1.0.3` out the door, scopes for Google will first be supported in `v1.0.4`.

**Comment by leekelleher** [comment]
@abjerner Just checking if you made any start/progress on the Google scopes?

I'm working on a project where I need to set the [`AnalyticsScope`](http://social.skybrud.dk/google/analytics/scope/). If the property-editor supported this, that would be great.  I'm happy to roll my sleeves up and help out if needed.  Just wanted to make sure you hadn't already made a start with it? (I couldn't tell from the repo)
